### ISSUE TITLE
great stuff but..

### ISSUE THREAD

**Issue by aztecsensei** [ashrafulislambd/fpscontroller#1]
please can u add the stairs and ladder just like in the jeramy tutorial:
https://www.youtube.com/watch?v=0BSlIpJ0wl8
https://www.youtube.com/watch?v=AvUYR2lzhEQ

thank you.

**Comment by ashrafulislambd** [comment]
Dear aztecsensei,
Thank you very much for your valuable comment. We'll add this in later version
