### ISSUE TITLE
settings values in const causes error

### ISSUE THREAD

**Issue by tofuhead** [ashrafulislambd/fpscontroller#11]
I tried your controller, got error while running, because you are defining consts, but then assigning values to them?   I changed them to vars and it started working.

```
const SENSITIVITY_Y = 0
const INVERSION_MULT = 1
const MAX_Y = 89

func initializeComponents():
	SENSITIVITY_Y = self.get_parent().Sensitivity_Y
```

**Comment by ashrafulislambd** [comment]
Ok changing to vars

**Comment by ashrafulislambd** [comment]
Another pull request has been merged and that contains the same solution you specified
