### ISSUE TITLE
Put scripts and scene in their own directory

### ISSUE THREAD

**Issue by Wavesonics** [ashrafulislambd/fpscontroller#2]
That way when this is added from the asset store, there's no chance these files will conflict with files already in the user's project.

Plus it is just nice to keep things organized.

> fpscontroller/Camera.gd
> fpscontroller/KinematicBody.gd
> fpscontroller/ToBeDropped.tscn

**Comment by ashrafulislambd** [comment]
My standard is not to keep Script/Scene in seperate directory. It is not actually a good oragnization. Suppose you have models, animations, actors etc in game: then you may follow this structure:
scene/
--model1.tscn
--model2.tscn
--....
--modeln.tscn
script/
--script1.gd
--script2.gd
-----
--scriptn.gd
Same for other directories. But it is not a good practice. A better practice is:
models/
--model1/
----model1.tscn
----model1.gd
--model2/
----####
----####
actors/
-----actor1/
---------actor1.tscn
---------actor1.gd

I hope this makes sense. I follow this type of organizations in my own projects and it is well managed.

**Comment by ashrafulislambd** [comment]
Finally if you want you can move all the files to a directory "FPS Controller"
